### PR TITLE
Add es6 support

### PR DESCRIPTION
**Pull request by rafayepes**
Changed from esprima to esprima-fb. Now it seems to parse well files with ES6 syntax

### CODE REVIEW

**Comment by pahen** [comment]
:+1:

**Comment by mixu** [comment]
:+1: thanks! Merged!

**Comment by mixu** [comment]
published as `v0.1.0`

**Comment by rafayepes** [comment]
Thanks!

**Comment by ariya** [comment]
Ah, this is not recommend. Facebook stopped maintaining their Esprima fork. Meanwhile, the latest Esprima 2.x has a complete ES6 support already (see among others https://groups.google.com/d/msg/esprima/2jEogfxzjqI/B4GzlxDnFAAJ).

I highly recommend updating to the latest Esprima 2.7.0 instead.

**Comment by rafayepes** [comment]
Oh, my bad. Missed that. Tried last version of Esprima and indeed seems to support ES6. And if Facebook fork is no longer supported, I believe that as @ariya said, it'll be better to update to last Esprima version.

Sorry for that guys!

**Comment by mixu** [comment]
updated to Esprima 2, published as `0.2.0`

**Pull request merged**
